name: Build and Test Express Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Node packages
        run: npm install

      - name: Run linting with ESLint
        run: npm run lint

      - name: Run formatting check with Prettier
        run: npm run format

      - name: Run testing suite with Jest and React Testing Library
        env:
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_KEY: ${{ secrets.SMTP_KEY }}
        run: npm run test
